# Assignment 1, 8-Puzzle Programming

#### Your homework must be implemented in this Notebook file. 
#### You can add as many cells as you want. However, you are not allowed to touch the code below the line "=============".
#### You need to implement the searching functions and the print result functions. The "print_result() function call after "====" line will print out the results in the format indicated in the Assignment description.
#### For the searching functions, feel free to customize the return data types and parameter lists as long as the function name is as required.

Write your name, netID and email here.

### Name: Mihir More
### NetID: bg4422
### Email: mmore@horizon.csueastbay.edu

a = 10
b = 12
a+b

In [1]:
t1 = 0
t2 = 0
counter = 0

In [2]:
import numpy as np 
import queue 
import time 
GOAL = [0, 1, 2, 3, 4, 5, 6, 7, 8]

class Puzzle():
    def __init__(self,current_state,parent_node,action_state,tree_depth,step_cost_factor,path_cost_factor):
        self.current_state = current_state 
        self.parent_node = parent_node 
        self.action_state = action_state 
        self.tree_depth = tree_depth 
        self.step_cost_factor = step_cost_factor 
        self.path_cost_factor = path_cost_factor        
        self.shift_up = None 
        self.shift_left = None
        self.shift_down = None
        self.shift_right = None
        step_counter = 0
        global counter 
    
    def move_right(self):
        initial_state_index=[i[0] for i in np.where(self.current_state==0)] 
        if initial_state_index[1] == 0:
            return False
        else:
            move_left_index_value = self.current_state[initial_state_index[0],initial_state_index[1]-1] 
            new_state = self.current_state.copy()
            new_state[initial_state_index[0],initial_state_index[1]] = move_left_index_value
            new_state[initial_state_index[0],initial_state_index[1]-1] = 0
            return new_state,move_left_index_value
        
    def move_up(self):
        initial_state_index=[i[0] for i in np.where(self.current_state==0)] 
        if initial_state_index[0] == 2:
            return False
        else:
            lower_index_value = self.current_state[initial_state_index[0]+1,initial_state_index[1]] # value of the lower tile
            new_state = self.current_state.copy()
            new_state[initial_state_index[0],initial_state_index[1]] = lower_index_value
            new_state[initial_state_index[0]+1,initial_state_index[1]] = 0
            return new_state,lower_index_value
        
    def move_down(self):
        initial_state_index=[i[0] for i in np.where(self.current_state==0)] 
        if initial_state_index[0] == 0:
            return False
        else:
            move_up_index_value = self.current_state[initial_state_index[0]-1,initial_state_index[1]] 
            new_state = self.current_state.copy()
            new_state[initial_state_index[0],initial_state_index[1]] = move_up_index_value
            new_state[initial_state_index[0]-1,initial_state_index[1]] = 0
            return new_state,move_up_index_value
        
    def move_left(self):
        initial_state_index=[i[0] for i in np.where(self.current_state==0)] 
        if initial_state_index[1] == 2:
            return False
        else:
            move_right_value = self.current_state[initial_state_index[0],initial_state_index[1]+1] # value of the move_right tile
            new_state = self.current_state.copy()
            new_state[initial_state_index[0],initial_state_index[1]] = move_right_value
            new_state[initial_state_index[0],initial_state_index[1]+1] = 0
            return new_state,move_right_value
        
    def path_trace(self):
        global counter
        current_state_trace = [self.current_state]
        action_state_trace = [self.action_state]
        tree_depth_trace = [self.tree_depth]
        step_cost_factor_trace = [self.step_cost_factor]
        path_cost_factor_trace = [self.path_cost_factor]     
        
        while self.parent_node:
            self = self.parent_node
            current_state_trace.append(self.current_state)
            action_state_trace.append(self.action_state)
            tree_depth_trace.append(self.tree_depth)
            step_cost_factor_trace.append(self.step_cost_factor)
            path_cost_factor_trace.append(self.path_cost_factor)            
        step_counter = 0
        print(self.current_state)
        while current_state_trace:         
            print('to')
            print (current_state_trace.pop())            
            step_counter += 1     
        counter = step_counter  
        print(counter)

In [3]:
#implementation of function "Iterative_deepening_DFS"

def iterative_deepening_DFS(self, goal_state):
        start_time = time.time() 
        global t1
        q_elem = 0 
        max_q_length = 1         
        for max_tree_depth in range(50):
            queue = [self] 
            tree_depth_queue = [0] 
            path_cost_queue = [0] 
            visited = set([]) 
            while queue:                
                if len(queue) > max_q_length:
                    max_q_length = len(queue)
                current_node = queue.pop(0)                 
                q_elem += 1 
                current_tree_depth = tree_depth_queue.pop(0)                
                current_path = path_cost_queue.pop(0) 
                visited.add(tuple(current_node.current_state.reshape(1,9)[0]))               
                if np.array_equal(current_node.current_state,goal_state):
                    print('Iterative deepening tree_depth-first search :')
                    current_node.path_trace()
                    t1 += time.time()-start_time
                    
                    return ' '

                else:              
                    if current_tree_depth < max_tree_depth:
                        if current_node.move_up():
                            new_state,lower_value = current_node.move_up()
                            
                            if tuple(new_state.reshape(1,9)[0]) not in visited:
                                
                                current_node.shift_up = Puzzle(current_state=new_state,parent_node=current_node,action_state='up',tree_depth=current_tree_depth+1,\
                                                      step_cost_factor=lower_value,path_cost_factor=current_path+lower_value)
                                queue.insert(0,current_node.shift_up)
                                tree_depth_queue.insert(0,current_tree_depth+1)
                                path_cost_queue.insert(0,current_path+lower_value)                
                       
                        if current_node.move_down():
                            new_state,up_value = current_node.move_down()
                            
                            if tuple(new_state.reshape(1,9)[0]) not in visited:
                                
                                current_node.shift_down = Puzzle(current_state=new_state,parent_node=current_node,action_state='down',tree_depth=current_tree_depth+1,\
                                                      step_cost_factor=up_value,path_cost_factor=current_path+up_value)
                                queue.insert(0,current_node.shift_down)
                                tree_depth_queue.insert(0,current_tree_depth+1)
                                path_cost_queue.insert(0,current_path+up_value)
                                
                        if current_node.move_right():
                            new_state,left_value = current_node.move_right()
                            
                            if tuple(new_state.reshape(1,9)[0]) not in visited:
                                
                                current_node.shift_right = Puzzle(current_state=new_state,parent_node=current_node,action_state='right',tree_depth=current_tree_depth+1,\
                                                      step_cost_factor=left_value,path_cost_factor=current_path+left_value)
                                queue.insert(0,current_node.shift_right)
                                tree_depth_queue.insert(0,current_tree_depth+1)
                                path_cost_queue.insert(0,current_path+left_value)

                        if current_node.move_left():
                            new_state,right_value = current_node.move_left()
                            
                            if tuple(new_state.reshape(1,9)[0]) not in visited:
                               
                                current_node.shift_left = Puzzle(current_state=new_state,parent_node=current_node,action_state='left',tree_depth=current_tree_depth+1,\
                                                      step_cost_factor=right_value,path_cost_factor=current_path+right_value)
                                queue.insert(0,current_node.shift_left)
                                tree_depth_queue.insert(0,current_tree_depth+1)
                                path_cost_queue.insert(0,current_path+right_value)

In [4]:
#implementation of function "breadthFirstSearch" 
def breadthFirstsearch(self, goal_state):
        start_time = time.time() 
        global t2
        queue = [self] 
        q_elem = 0 
        max_q_len = 1         
        depth_queue = [0] 
        path_cost_queue = [0] 
        visited = set([])
        compare = False
        while queue:
            
            if len(queue) > max_q_len:
                max_q_len = len(queue)                
            current_node = queue.pop(0) 
            q_elem += 1 
            
            current_depth = depth_queue.pop(0) 
            present_pc = path_cost_queue.pop(0) 
            visited.add(tuple(current_node.current_state.reshape(1,9)[0])) 
            if np.array_equal(current_node.current_state,goal_state):
                print('Breadth First Search :')
                current_node.path_trace()
                t2 += (time.time()-start_time)
                
                return ' '
            
            else:
                if current_node.move_up():
                    new_state,lower_value = current_node.move_up()
                   
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                       
                        current_node.shift_up = Puzzle(current_state=new_state,parent_node=current_node,action_state='up',tree_depth=current_depth+1,\
                                              step_cost_factor=lower_value,path_cost_factor=present_pc+lower_value)
                        queue.append(current_node.shift_up)
                        depth_queue.append(current_depth+1)
                        path_cost_queue.append(present_pc+lower_value)
               
                if current_node.move_down():
                    new_state,up_value = current_node.move_down()
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                        
                        current_node.shift_down = Puzzle(current_state=new_state,parent_node=current_node,action_state='down',tree_depth=current_depth+1,\
                                              step_cost_factor=up_value,path_cost_factor=present_pc+up_value)
                        queue.append(current_node.shift_down)
                        depth_queue.append(current_depth+1)
                        path_cost_queue.append(present_pc+up_value)                    
                
                if current_node.move_right():
                    new_state,left_value = current_node.move_right()
                    
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                        
                        current_node.shift_right = Puzzle(current_state=new_state,parent_node=current_node,action_state='right',tree_depth=current_depth+1,\
                                              step_cost_factor=left_value,path_cost_factor=present_pc+left_value)
                        queue.append(current_node.shift_right)
                        depth_queue.append(current_depth+1)
                        path_cost_queue.append(present_pc+left_value)                       
                 
                if current_node.move_left():
                    new_state,right_value = current_node.move_left()
                  
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                     
                        current_node.shift_left = Puzzle(current_state=new_state,parent_node=current_node,action_state='left',tree_depth=current_depth+1,\
                                              step_cost_factor=right_value,path_cost_factor=present_pc+right_value)
                        queue.append(current_node.shift_left)
                        depth_queue.append(current_depth+1)
                        path_cost_queue.append(present_pc+right_value)
                        
        while compare == True:            
            queue = sorted(queue, key=lambda x: x[1])
            depth_queue = sorted(depth_queue, key=lambda x: x[1])
            path_cost_queue = sorted(path_cost_queue, key=lambda x: x[1])          
            
            if len(queue) > queue_max_length:
                queue_max_length = len(queue)
                
            current_node = queue.pop(0)[0]            
            queue_num_nodes_popped += 1 
            current_depth = depth_queue.pop(0)[0] 
            current_path_cost = path_cost_queue.pop(0)[0] 
            visited.add(tuple(current_node.state.reshape(1,9)[0])) 

In [5]:
#implementation of function "print_result(result)"
def print_result():    
    increment = 0
    global counter
    temp = 0
    with open('Input8PuzzleCases.txt') as file:
        listRead = file.readlines()
        for i in range(10):            
        #string to list
        
            list_input = listRead[i].split(',')
            list_input = [int(x) for x in list_input]
            print("Starting State: ",list_input)
            starting_state = np.array(list_input).reshape(3,3)
            goal_state = np.array([0,1,2,3,4,5,6,7,8]).reshape(3,3)
            root_node = Puzzle(current_state = starting_state,parent_node = None,action_state = None,tree_depth = 0,step_cost_factor = 0,path_cost_factor=0)   
            print(iterative_deepening_DFS(root_node,goal_state))
            counter += counter
            print(counter)
            
        temp = counter
        counter = 0
    file.close()
    with open('Input8PuzzleCases.txt') as file:
        listRead = file.readlines()
        for i in range(10):            
        #string to list
        
            list_input = listRead[i].split(',')
            list_input = [int(x) for x in list_input]
            print("Starting State: ",list_input)
            starting_state = np.array(list_input).reshape(3,3)
            goal_state = np.array([0,1,2,3,4,5,6,7,8]).reshape(3,3)
            root_node = Puzzle(current_state = starting_state,parent_node = None,action_state = None,tree_depth = 0,step_cost_factor = 0,path_cost_factor=0)              
            print(breadthFirstsearch(root_node,goal_state))
            counter += counter  
            print(counter)
    file.close()
    print('\t'+ 'Average_steps'+'\t'+'Average_time')
    print('IDS :'+'\t'+str(temp/2)+'\t'+'\t'+str(round(t1/100,2))+'s')
    print('BFS :'+'\t'+str(counter/2)+'\t'+'\t'+str(round(t2/100,2))+'s')
    
    #[Reference](https://www.geeksforgeeks.org/8-puzzle-problem-using-branch-and-bound/)

## You can insert as many cells as you want above
## You are not Allowed to modify the code below this line.

# ============================================================

In [6]:
#you need to implement print_result function to print out the result according to the required format
print_result()

Starting State:  [8, 7, 5, 4, 1, 2, 3, 0, 6]
Iterative deepening tree_depth-first search :
[[8 7 5]
 [4 1 2]
 [3 0 6]]
to
[[8 7 5]
 [4 1 2]
 [3 0 6]]
to
[[8 7 5]
 [4 1 2]
 [3 6 0]]
to
[[8 7 5]
 [4 1 0]
 [3 6 2]]
to
[[8 7 5]
 [4 0 1]
 [3 6 2]]
to
[[8 7 5]
 [0 4 1]
 [3 6 2]]
to
[[8 7 5]
 [3 4 1]
 [0 6 2]]
to
[[8 7 5]
 [3 4 1]
 [6 0 2]]
to
[[8 7 5]
 [3 4 1]
 [6 2 0]]
to
[[8 7 5]
 [3 4 0]
 [6 2 1]]
to
[[8 7 0]
 [3 4 5]
 [6 2 1]]
to
[[8 0 7]
 [3 4 5]
 [6 2 1]]
to
[[0 8 7]
 [3 4 5]
 [6 2 1]]
to
[[3 8 7]
 [0 4 5]
 [6 2 1]]
to
[[3 8 7]
 [4 0 5]
 [6 2 1]]
to
[[3 8 7]
 [4 5 0]
 [6 2 1]]
to
[[3 8 7]
 [4 5 1]
 [6 2 0]]
to
[[3 8 7]
 [4 5 1]
 [6 0 2]]
to
[[3 8 7]
 [4 0 1]
 [6 5 2]]
to
[[3 0 7]
 [4 8 1]
 [6 5 2]]
to
[[3 7 0]
 [4 8 1]
 [6 5 2]]
to
[[3 7 1]
 [4 8 0]
 [6 5 2]]
to
[[3 7 1]
 [4 8 2]
 [6 5 0]]
to
[[3 7 1]
 [4 8 2]
 [6 0 5]]
to
[[3 7 1]
 [4 0 2]
 [6 8 5]]
to
[[3 0 1]
 [4 7 2]
 [6 8 5]]
to
[[3 1 0]
 [4 7 2]
 [6 8 5]]
to
[[3 1 2]
 [4 7 0]
 [6 8 5]]
to
[[3 1 2]
 [4 7 5]
 [6 8 0]]
to
[[3 1 2]
 

Iterative deepening tree_depth-first search :
[[6 5 2]
 [1 4 8]
 [0 7 3]]
to
[[6 5 2]
 [1 4 8]
 [0 7 3]]
to
[[6 5 2]
 [1 4 8]
 [7 0 3]]
to
[[6 5 2]
 [1 4 8]
 [7 3 0]]
to
[[6 5 2]
 [1 4 0]
 [7 3 8]]
to
[[6 5 2]
 [1 0 4]
 [7 3 8]]
to
[[6 0 2]
 [1 5 4]
 [7 3 8]]
to
[[0 6 2]
 [1 5 4]
 [7 3 8]]
to
[[1 6 2]
 [0 5 4]
 [7 3 8]]
to
[[1 6 2]
 [5 0 4]
 [7 3 8]]
to
[[1 6 2]
 [5 3 4]
 [7 0 8]]
to
[[1 6 2]
 [5 3 4]
 [0 7 8]]
to
[[1 6 2]
 [0 3 4]
 [5 7 8]]
to
[[1 6 2]
 [3 0 4]
 [5 7 8]]
to
[[1 0 2]
 [3 6 4]
 [5 7 8]]
to
[[0 1 2]
 [3 6 4]
 [5 7 8]]
to
[[3 1 2]
 [0 6 4]
 [5 7 8]]
to
[[3 1 2]
 [6 0 4]
 [5 7 8]]
to
[[3 1 2]
 [6 4 0]
 [5 7 8]]
to
[[3 1 2]
 [6 4 8]
 [5 7 0]]
to
[[3 1 2]
 [6 4 8]
 [5 0 7]]
to
[[3 1 2]
 [6 4 8]
 [0 5 7]]
to
[[3 1 2]
 [0 4 8]
 [6 5 7]]
to
[[3 1 2]
 [4 0 8]
 [6 5 7]]
to
[[3 1 2]
 [4 5 8]
 [6 0 7]]
to
[[3 1 2]
 [4 5 8]
 [6 7 0]]
to
[[3 1 2]
 [4 5 0]
 [6 7 8]]
to
[[3 1 2]
 [4 0 5]
 [6 7 8]]
to
[[3 1 2]
 [0 4 5]
 [6 7 8]]
to
[[0 1 2]
 [3 4 5]
 [6 7 8]]
29
 
58
Starting State:  [0

Breadth First Search :
[[6 5 2]
 [1 4 8]
 [0 7 3]]
to
[[6 5 2]
 [1 4 8]
 [0 7 3]]
to
[[6 5 2]
 [0 4 8]
 [1 7 3]]
to
[[6 5 2]
 [4 0 8]
 [1 7 3]]
to
[[6 0 2]
 [4 5 8]
 [1 7 3]]
to
[[0 6 2]
 [4 5 8]
 [1 7 3]]
to
[[4 6 2]
 [0 5 8]
 [1 7 3]]
to
[[4 6 2]
 [1 5 8]
 [0 7 3]]
to
[[4 6 2]
 [1 5 8]
 [7 0 3]]
to
[[4 6 2]
 [1 5 8]
 [7 3 0]]
to
[[4 6 2]
 [1 5 0]
 [7 3 8]]
to
[[4 6 2]
 [1 0 5]
 [7 3 8]]
to
[[4 0 2]
 [1 6 5]
 [7 3 8]]
to
[[0 4 2]
 [1 6 5]
 [7 3 8]]
to
[[1 4 2]
 [0 6 5]
 [7 3 8]]
to
[[1 4 2]
 [6 0 5]
 [7 3 8]]
to
[[1 4 2]
 [6 3 5]
 [7 0 8]]
to
[[1 4 2]
 [6 3 5]
 [0 7 8]]
to
[[1 4 2]
 [0 3 5]
 [6 7 8]]
to
[[1 4 2]
 [3 0 5]
 [6 7 8]]
to
[[1 0 2]
 [3 4 5]
 [6 7 8]]
to
[[0 1 2]
 [3 4 5]
 [6 7 8]]
21
 
42
Starting State:  [0, 6, 1, 3, 4, 7, 8, 5, 2]
Breadth First Search :
[[0 6 1]
 [3 4 7]
 [8 5 2]]
to
[[0 6 1]
 [3 4 7]
 [8 5 2]]
to
[[3 6 1]
 [0 4 7]
 [8 5 2]]
to
[[3 6 1]
 [4 0 7]
 [8 5 2]]
to
[[3 0 1]
 [4 6 7]
 [8 5 2]]
to
[[0 3 1]
 [4 6 7]
 [8 5 2]]
to
[[4 3 1]
 [0 6 7]
 [8 5 2]]
to
[[4 3


# The output format should be as follows. You only need to give one sample solution as an example.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Solution of the first Scenario:
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### .
#### .
#### .
#### 0 1 2
#### 3 4 5
#### 6 7 8

                Average_Steps    Average_Time      
 IDS
 
 BFS

